---
title: Oslo Barnemuseum
timezone: Europe/Copenhagen
collections:
  posts:
    title: Innlegg
    output: true
    description: ''
    feature_text: ''
    feature_image: https://raw.githubusercontent.com/lassegs/obmimg/master/IMG_33051.jpg
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    image: "/assets/default-social-image.png"
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: "/assets/default-social-image.png"
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
paginate: 4
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
twitter:
  username: oslobarnemuseum
author: Oslobarnemuseum
social:
  name: Oslo Barnemuseum
  links:
  - https://twitter.com/oslobarnemuseum
  - https://www.facebook.com/oslobarnemuseum
  - https://www.linkedin.com/in/oslobarnemuseum
  - https://plus.google.com/+oslobarnemuseum
  - https://https://github.com/katieco/oslobarnemuseum
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
logo: "/assets/obm_logo1.png"
description: Er det ikke på tide at vi kan få et interaktivt barnemuseum i Oslo til
  nytte og glede for barn, familier, lærere, turister og andre?
url: https://katieco.github.io/oslobarnemuseum
baseurl: "/oslobarnemuseum"
repo: https://github.com/katieco/oslobarnemuseum
email: info@oslobarnemuseum.org
avatarurl: "/assets/favicon.png"
navigation_header:
  Tilbud: "/"
  Om: "/om/"
  Aktiviteter: "/aktiviteter/"
  Nyheter: "/blog/"
  Kontakt: "/kontakt/"
navigation_footer:
  Samskapt: https://github.com/katieco/oslobarnemuseum
social_links:
  Twitter: https://twitter.com/oslobarnemuseum
  Facebook: https://www.facebook.com/oslobarnemuseum
  GitHub: https://github.com/katieco/oslobarnemuseum
  RSS: "/feed.xml"
sharing_links:
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  Email: " #FF851B "
